stages:
  - build
  - test

# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mysql-test
  DB_CONNECTION: mysql

build:
  stage: build
  services:
    - name: mysql:5.7
      alias: mysql-test

  image: chilio/laravel-dusk-ci:stable
  script:
    - versions
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - npm install
    - npm run dev
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor
      - node_modules

test:
  stage: test
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - vendor
      - node_modules
    policy: pull

  services:
    - name: mysql:5.7
      alias: mysql-test

  image: chilio/laravel-dusk-ci:stable
  script:
    - cp .env.testing .env
    - cp phpunit.xml.ci phpunit.xml
    - configure-laravel
    - start-nginx-ci-project
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors --stderr
    - php artisan dusk --colors --debug

  artifacts:
    paths:
      - ./storage/logs
      - ./tests/Browser/screenshots
      - ./tests/Browser/console
    expire_in: 7 days
    when: always
