stages:
  - tests

cache:
  key: $CI_BUILD_REF_NAME
  paths:
    - vendor

insights:
  stage: tests
  image: lorisleiva/laravel-docker:7.3
  script:
    - composer install --no-ansi --no-interaction --no-progress
    - php artisan insights --no-interaction --min-quality=80 --min-complexity=90 --min-architecture=75 --min-style=95
