name: Tests
on: [push]
jobs:
  assets:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Dependencies
        run: npm install
      - name: Build
        run: npm run prod
  tests-dusk:
    name: Browser Tests
    runs-on: ubuntu-latest
    container: docker://chilio/laravel-dusk-ci:stable
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: lights-controls
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@master
      - name: Before Tests
        run: |
          cp .env.testing .env
          configure-laravel
          npm install
          npm run prod
          start-nginx-ci-project
          cp .phpunit.dusk.xml phpunit.xml
      - name: Tests
        run: php artisan dusk
