name: Tests
on: [push]
jobs:
  assets:
    name: Build Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Download Dependencies
        run: npm install
      - name: Build
        run: npm run prod
  tests-dusk:
    name: Browser Tests
    runs-on: ubuntu-latest
    container: docker://zaherg/laravel-dusk:latest
    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: homestead
          MYSQL_PASSWORD: secret
          MYSQL_DATABASE: homestead
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
    steps:
      - uses: actions/checkout@master
      - name: Download Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - name: Setup Laravel
        run: |
          cp .env.testing .env
          cp .phpunit.dusk.xml phpunit.xml
          chmod -R 775 storage
          chmod 775 bootstrap/
          php artisan key:generate
          php artisan storage:link
          php artisan migrate:fresh --seed
      - name: Assets Download & Build
        run : |
          npm install
          npm run prod
      - name: Upgrade chrome driver
        run: php artisan dusk:chrome-driver
      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux > /dev/null 2>&1 &
      - name: Run Laravel Server
        run: php artisan serve > /dev/null 2>&1 &
      - name: Run dusk tests
        run: php artisan dusk
  lint:
    name: Lint & Insights
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Before Tests
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - name: Lint
        run: php artisan insights --no-interaction --min-quality=80 --min-complexity=75 --min-architecture=90 --min-style=95
